version: "3.8"

services:

  redis-0:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - redis-data-0:/data
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-1:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - redis-data-1:/data
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-2:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - redis-data-2:/data
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-3:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - redis-data-3:/data
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-4:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - redis-data-4:/data
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster

networks:
  redis-cluster: {}

volumes:
  redis-data-0:
    driver: local
  redis-data-1:
    driver: local
  redis-data-2:
    driver: local
  redis-data-3:
    driver: local
  redis-data-4:
    driver: local