version: "3.8"

services:

  redis-0:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-1:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-2:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-3:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-4:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster
  redis-5:
    image: redis:4.0.11
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./cluster.conf:/etc/redis/cluster.conf
    networks:
      - redis-cluster

networks:
  redis-cluster: {}
