version: "3.8"

services:

  redis-1:
    image: redis:4.0.11-alpine
    command: /etc/redis/cluster.conf
    expose:
      - 6379
    volumes:
      - ./conf/cluster-01.conf:/etc/redis/cluster.conf
    network_mode: host
  redis-2:
    image: redis:4.0.11-alpine
    command: /etc/redis/cluster.conf
    expose:
      - 6380
    volumes:
      - ./conf/cluster-02.conf:/etc/redis/cluster.conf
    network_mode: host
  redis-3:
    image: redis:4.0.11-alpine
    command: /etc/redis/cluster.conf
    expose:
      - 6381
    volumes:
      - ./conf/cluster-03.conf:/etc/redis/cluster.conf
    network_mode: host
  redis-4:
    image: redis:4.0.11-alpine
    command: /etc/redis/cluster.conf
    expose:
      - 6382
    volumes:
      - ./conf/cluster-04.conf:/etc/redis/cluster.conf
    network_mode: host
  redis-5:
    image: redis:4.0.11-alpine
    command: /etc/redis/cluster.conf
    expose:
      - 6383
    volumes:
      - ./conf/cluster-05.conf:/etc/redis/cluster.conf
    network_mode: host
  redis-6:
    image: redis:4.0.11-alpine
    command: /etc/redis/cluster.conf
    expose:
      - 6384
    volumes:
      - ./conf/cluster-06.conf:/etc/redis/cluster.conf
    network_mode: host
