version: "3.8"

services:
  # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#google-auth-provider
  # Requirements:
  # - cookie secret: python -c 'import os,base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'
  oauth-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    command:
      - --http-address
      - 0.0.0.0:4180
      - --client-id
      - ${OAUTH_CLIENT_ID}
      - --client-secret
      - ${OAUTH_CLIENT_SECRET}
      - --cookie-secret
      - "B47kp72tIxr8UlIBxtifDu05iWp7dtElmrvBnQdibbA="
      - --email-domain
      - ${OAUTH_EMAIL_DOMAIN}
      - --cookie-refresh
      - 3600s
    expose:
      - 4180
  reverse-proxy:
    image: nginx:1.20.1-alpine
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
  # https://www.elastic.co/guide/en/kibana/5.0/index.html
  kibana:
    image: kibana:5.6.16
    expose:
      - 5601
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "5601"
      ELASTICSEARCH_URL: "http://elastic:9200"
  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/index.html
  # Requirements
  # - sudo sysctl vm.max_map_count=262144
  elastic:
    image: elasticsearch:5.6.16
    expose:
      - 9200
    environment:
      DISCOVERY_TYPE: "single-node"
      NODE_NAME: "elasticsearch-0"
      NETWORK_HOST: "0.0.0.0"
